version: "3.8"

services:
  tensorflow-serving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./models/model:/models/model
    restart: always

  classifier:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - tensorflow-serving
    restart: always